---
sudo: required
language: python

services:
  - docker

script:
  - bash build.sh

before_deploy:
  - tar -zcvf ${TRAVIS_REPO_SLUG#*/}.tar.gz -C _site ./
  - sha256sum --tag ${TRAVIS_REPO_SLUG#*/}.tar.gz > SHASUMS
  - export BODY="$(cat SHASUMS)"

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
    - ${TRAVIS_REPO_SLUG#*/}.tar.gz
    - SHASUMS
  body: ${BODY}
  skip_cleanup: true
  on:
    tags: true
